# Generated by Django 5.2.6 on 2025-12-13 15:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Le titre doit avoir au moins 6 caractères'), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='Le titre ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')])),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='La description ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='Le lieu ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')])),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], max_length=50)),
                ('visibilite', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé')], max_length=50)),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Nombre maximum de participants')),
                ('featured', models.BooleanField(default=False, help_text='Événement à la une')),
                ('promotion_image', models.FileField(blank=True, help_text='Image de promotion', null=True, upload_to='promotions/')),
                ('promotion_description', models.TextField(blank=True, help_text='Description de promotion', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='appEvenements.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evenement', 'user')},
            },
        ),
    ]
