# Generated by Django 5.2.6 on 2025-11-30 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='ID de la page Facebook du club', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='La description ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')]),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='Le lieu ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')]),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Le titre doit avoir au moins 6 caractères'), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,!?-]+$', message='Le titre ne peut contenir que des lettres, chiffres, espaces et ponctuation basique.')]),
        ),
    ]
