# Generated by Django 5.2.6 on 2025-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvenements', '0002_evenement_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='facebook_page_id',
        ),
        migrations.AddField(
            model_name='evenement',
            name='image_pro',
            field=models.ImageField(blank=True, help_text="Image de promotion pour la page d'accueil (optionnel)", null=True, upload_to='evenements/promotion/'),
        ),
    ]
