# Generated by Django 5.2.6 on 2025-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvenements', '0003_remove_evenement_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='featured',
            field=models.BooleanField(default=True, help_text="Afficher cet événement à la une sur la page d'accueil"),
        ),
    ]
