# Generated by Django 5.2.6 on 2025-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvenements', '0004_evenement_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='promotion_description',
            field=models.TextField(blank=True, help_text='Description de promotion', null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='promotion_image',
            field=models.ImageField(blank=True, help_text='Image de promotion', null=True, upload_to='promotions/'),
        ),
    ]
