# Generated by Django 5.2.6 on 2025-12-24 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphanumeric characters and spaces.', regex='^[A-Za-z0-9\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long.')])),
                ('established_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Demande_creation_club',
            fields=[
                ('demande_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphanumeric characters and spaces.', regex='^[A-Za-z0-9\\s]+$')])),
                ('club_description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long.')])),
                ('president_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphabetic characters and spaces.', regex='^[A-Za-z\\s]+$')])),
                ('vice_president_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphabetic characters and spaces.', regex='^[A-Za-z\\s]+$')])),
                ('requested_by', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphabetic characters and spaces.', regex='^[A-Za-z\\s]+$')])),
                ('emailResponsable', models.EmailField(blank=True, max_length=254, null=True)),
                ('emailClub', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999'. Up to 8 digits allowed.", regex='^\\+?\\d{8}$')])),
            ],
        ),
    ]
