# Generated by Django 5.2.8 on 2025-11-08 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should contain only alphanumeric characters and spaces.', regex='^[A-Za-z0-9\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long.')])),
                ('established_date', models.DateField()),
            ],
        ),
    ]
