# Generated by Django 5.2.8 on 2025-12-09 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_replace_club_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='club',
            field=models.OneToOneField(blank=True, help_text='Chaque club peut posséder au plus un forum privé.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='forum.club', verbose_name='Club associé'),
        ),
    ]
