# Generated by Django 5.2.6 on 2025-11-09 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Le titre doit avoir au moins 6 caractères'), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$')])),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000), django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$')])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$')])),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], max_length=50)),
                ('visibilite', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé')], max_length=50)),
            ],
        ),
    ]
