# Generated by Django 5.2.6 on 2025-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvenements', '0005_evenement_promotion_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='image_pro',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='featured',
            field=models.BooleanField(default=False, help_text='Événement à la une'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='promotion_image',
            field=models.ImageField(blank=True, help_text='Image de promotion', null=True, upload_to='feat_pic/'),
        ),
    ]
