# Generated by Django 5.2.8 on 2025-12-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('forum', '0008_replace_club_field'),
    ]

    operations = [
    ]
