# Generated by Django 5.2.8 on 2025-12-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_add_thread_fields'),
        ('forum', '0010_create_notification'),
        ('forum', 'XXXX_add_missing_fields'),
    ]

    operations = [
    ]
