# Generated by Django 5.2.7 on 2025-11-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('eligibility', models.CharField(choices=[('member', 'Membre'), ('organizer', 'Organisateur')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archivée')], default='active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/')),
                ('category', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('member', 'Membre'), ('organizer', 'Organisateur'), ('admin', 'Administrateur')], max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='resources.aid')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_submitted'],
                'unique_together': {('aid', 'applicant')},
            },
        ),
    ]
