# Generated by Django 5.2.7 on 2025-11-07 15:15

import django.db.models.deletion
from django.db import migrations, models


RESOURCE_TYPE = 'resource'
AID_TYPE = 'aid'


def forwards_populate_categories(apps, schema_editor):
    Category = apps.get_model('resources', 'Category')
    Resource = apps.get_model('resources', 'Resource')
    Aid = apps.get_model('resources', 'Aid')

    # Resources
    for resource in Resource.objects.all():
        name = getattr(resource, 'category', None)
        if not name:
            continue
        category_obj, _ = Category.objects.get_or_create(
            name=name,
            defaults={'type': RESOURCE_TYPE},
        )
        if category_obj.type != RESOURCE_TYPE:
            category_obj.type = RESOURCE_TYPE
            category_obj.save(update_fields=['type'])
        resource.category_temp = category_obj
        resource.save(update_fields=['category_temp'])

    # Aids
    for aid in Aid.objects.all():
        name = getattr(aid, 'category', None)
        if not name:
            continue
        category_obj, _ = Category.objects.get_or_create(
            name=name,
            defaults={'type': AID_TYPE},
        )
        if category_obj.type != AID_TYPE:
            category_obj.type = AID_TYPE
            category_obj.save(update_fields=['type'])
        aid.category_temp = category_obj
        aid.save(update_fields=['category_temp'])


def backwards_restore_categories(apps, schema_editor):
    Category = apps.get_model('resources', 'Category')
    Resource = apps.get_model('resources', 'Resource')
    Aid = apps.get_model('resources', 'Aid')

    # Restore string values from FK
    for resource in Resource.objects.all():
        category = getattr(resource, 'category_temp', None)
        if category:
            resource.category = category.name
            resource.save(update_fields=['category'])

    for aid in Aid.objects.all():
        category = getattr(aid, 'category_temp', None)
        if category:
            aid.category = category.name
            aid.save(update_fields=['category'])

    # Cleaning up category entries is optional; keep them for data integrity


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('resource', 'Ressource'), ('aid', 'Aide')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.category'),
        ),
        migrations.AddField(
            model_name='aid',
            name='category_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.category'),
        ),
        migrations.RunPython(forwards_populate_categories, backwards_restore_categories),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='category',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='category_temp',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='aid',
            old_name='category_temp',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': RESOURCE_TYPE}, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.category'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': AID_TYPE}, on_delete=django.db.models.deletion.PROTECT, related_name='aids', to='resources.category'),
        ),
    ]
