# Generated by Django 5.2.7 on 2025-11-07 15:26

from django.db import migrations


RESOURCE_DEFAULTS = [
    "Document",
    "Présentation",
    "Formation",
    "Événement",
    "Rapport",
]

AID_DEFAULTS = [
    "Financière",
    "Logistique",
    "Matérielle",
    "Communication",
]


def seed_default_categories(apps, schema_editor):
    Category = apps.get_model("resources", "Category")

    if Category.objects.exists():
        return

    # Create defaults for resources
    Category.objects.bulk_create(
        [
            Category(name=name, type="resource")
            for name in RESOURCE_DEFAULTS
        ]
        + [
            Category(name=name, type="aid")
            for name in AID_DEFAULTS
        ]
    )


def unseed_default_categories(apps, schema_editor):
    Category = apps.get_model("resources", "Category")
    Category.objects.filter(name__in=RESOURCE_DEFAULTS + AID_DEFAULTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_category_alter_aid_category_alter_resource_category'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, unseed_default_categories),
    ]
