# Generated by Django 5.2.7 on 2025-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
    ]
