# Generated by Django 5.2.7 on 2025-11-08 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_club_aid_club_resource_club_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='club',
        ),
        migrations.AlterModelOptions(
            name='aid',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='aidrequest',
            options={'ordering': ['-date_requested']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterUniqueTogether(
            name='aidrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aid',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.RemoveField(
            model_name='club',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='aid',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de soumission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aid',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='aids/', verbose_name='Fichier'),
        ),
        migrations.AddField(
            model_name='aid',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_aids', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de demande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='description',
            field=models.TextField(default='Default description', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='type',
            field=models.CharField(choices=[('resource', 'Ressource'), ('aid', 'Aide')], default='aid', max_length=20, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de soumission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_resources', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aid',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aids', to='resources.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ResourceRequest',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='justification',
        ),
    ]
