# Generated by Django 5.2.8 on 2025-11-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_document_faqentry_fichepdf_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
