# Generated by Django 5.2.8 on 2025-11-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
